name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Update log file
        run: |
          echo "$(date) - keeping green streak alive" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name 'bhargavIT1'
          git config --global user.email 'your-bhargavbora79@gmail.com'
          git add log.txt
          git commit -m "Daily commit to keep streak alive" || echo "Nothing to commit"
          git push
