name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Also allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: date >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name 'bhargavIT1'
          git config --global user.email 'your-bhagavbora79@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/bhargavIT1/Daily_Tracker.git
          git add .
          git commit -m "Daily commit to keep streak alive"
          git push
